name: "Python"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login into DockerHub
      run: echo ${{secrets.DOCKERHUB_TOKEN_RW}} | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin

    - name: Build Docker image from branch "${{github.ref_name}}" for Base Python
      run: docker build . --file python/Dockerfile --tag ${{secrets.DOCKERHUB_USER}}/base-python:${{github.ref_name}}

    - name: Push Docker image from branch "${{github.ref_name}}" for Base Python to DockerHub
      run: docker push ${{secrets.DOCKERHUB_USER}}/base-python:${{github.ref_name}}
