name: "Python AI (CPU)"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login into DockerHub
      run: echo ${{secrets.DOCKERHUB_TOKEN_RW}} | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin

    - name: Build Docker image for Base Python AI CPU locally
      run: docker build . --file python-ai-cpu/Dockerfile --tag ${{secrets.DOCKERHUB_USER}}/base-python-ai:latest-cpu

    - name: Push Docker image for Base Python AI CPU to DockerHub
      run: docker push ${{secrets.DOCKERHUB_USER}}/base-python-ai:latest-cpu
